name: ros_package_build

on:

  push:
    branches: [ ros2 ]

    paths-ignore:
      - '**/README.md'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    uses: ctu-mrs/ci_scripts/.github/workflows/ros_package_build.yml@ros2_tests_enabling
    with:
      RUN_TESTS: true
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
