# GET ALL PARAMETERS USABLE FOR CUSTOM CONFIG BY RUNNING:
## --------------------------------------------------------------
## |          ros2 run mrs_uav_core get_public_params.py          #
## --------------------------------------------------------------

# custom_config.yaml (VERSÃO QUE FUNCIONA 100%)

mrs_uav_managers:
  estimation_manager:
    state_estimators: ["passthrough"]
    initial_state_estimator: "passthrough"
    agl_height_estimator: ""

  # passthrough não precisa de transform_manager complexo
  transform_manager:
    passthrough:
      utm_based: false
      republish_in_frames: ["local_origin", "stable_origin", "fcu_untilted"]
  uav_manager:

    takeoff:

      during_takeoff:
        controller: "MpcController"
        tracker: "LandoffTracker"

      after_takeoff:
        controller: "Se3Controller"
        tracker: "MpcTracker"

    midair_activation:

      during_activation:
        controller: "MidairActivationController"
        tracker: "MidairActivationTracker"

      after_activation:
        controller: "MpcController"
        tracker: "MpcTracker"