# world_config.yaml
world_origin:
  units: "LATLON"
  origin_x: 47.397743
  origin_y: 8.545594

safety_area:
  enabled: false          # ← só essa linha muda tudo

  horizontal:
    frame_name: "world_origin"
    points: [...]
  vertical:
    frame_name: "world_origin"
    max_z: 15.0
    min_z: 0.5